version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: circleci/node
    
    steps:
      - checkout
      - run:
          name: Zipping the package
          command: zip -r << pipeline.number >> ./templates/
      - run: 
          name: installing aws cli
          command: |
            sudo apt-get update
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: creating a s3 bucket
          command: aws s3 mb s3://circle-ci-buckett --region $AWS_REGION
      - run: ls && pwd
      - run:
          working_directory: ./templates/
          name: copy the zip file into s3 bucket
          command: aws s3 cp /home/circleci/project/<< pipeline.number >>.zip s3://circle-ci-buckett --region $AWS_REGION



workflows:
  deploy:
    jobs:
      - build
